# Generated by Django 3.2.7 on 2021-09-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='p-dog.jpg', null=True, upload_to='images'),
        ),
    ]
