# Generated by Django 3.2.7 on 2021-09-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
